FROM php:7.4-fpm
RUN apt-get update && apt-get install -y libxml2-dev libzip-dev git unzip
RUN pecl install xdebug-2.8.1 \
    && docker-php-ext-enable xdebug
RUN docker-php-ext-install mysqli pdo_mysql soap zip opcache
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && cp composer.phar /bin/ \
    && mv /bin/composer.phar /bin/composer \
    && chmod +x /bin/composer
WORKDIR /app